spring:
#   sa-token配置
  sa-token:
    # token名称 (同时也是cookie名称)
    token-name: satoken
    # token有效期，单位s 默认30天, -1代表永不过期
    timeout: 2592000
    # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
    activity-timeout: 1800
    # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
    allow-concurrent-login: false
    # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
    is-share: false
    # token风格
    token-style: random-32
    #uuid风格
    #    token-style: simple-uuid  #uuid风格, 只不过去掉了中划线
    #    token-style: random-32    #随机32位字符串
    ##    token-style: random-64    #随机64位字符串
    ##    token-style: tik          #tik风格
    # 是否输出操作日志
#    tokenPrefix: Bearer
    is-log: false
    # 写入Cookie时显式指定的作用域, 用于单点登录二级域名共享Cookie
    cookie-domain: stp.com
    # Sa-Token-Quick-Login 配置
# Sa-Token-Quick-Login 配置
sa:
  # 登录账号
  name: s
  # 登录密码
  pwd: 1
  # 是否自动随机生成账号密码 (此项为true时, name与pwd失效)
  auto: false
  # 是否开启全局认证(关闭后将不再强行拦截)
  auth: true
  # 登录页标题
  title: Sa-Token 登录
  # 是否显示底部版权信息
  copr: true
